controllers:
   - name: 'dwa'
     type: 'dwa_local_planner/DWAPlannerROS'
   - name: 'teb'
     type: 'teb_local_planner/TebLocalPlannerROS'
   - name: 'eband'
     type: 'eband_local_planner/EBandPlannerROS'
   - name: 'eband_accurate'
     type: 'eband_local_planner/EBandPlannerROS'
eband:
  Ctrl_Rate: 20.0
  bubble_velocity_multiplier: 2.0
  costmap_weight: 10.0
  differential_drive: true
  disallow_hysteresis: false
  eband_equilibrium_approx_max_recursion_depth: 3
  eband_equilibrium_relative_overshoot: 0.75
  eband_external_force_gain: 3.0
  eband_internal_force_gain: 2.0
  eband_min_relative_overlap: 0.7
  eband_significant_force_lower_bound: 0.15
  eband_tiny_bubble_distance: 0.01
  eband_tiny_bubble_expansion: 0.01
  in_place_trans_vel: 0.0
  k_damp: 3.5
  k_prop: 4.0
  marker_lifetime: 0.5
  max_acceleration: 0.2
  max_rotational_acceleration: 0.3
  max_translational_acceleration: 0.4
  max_vel_lin: 1.45
  max_vel_th: 2.0
  min_in_place_vel_th: 0.05
  min_vel_lin: 0.0
  min_vel_th: 0.0
  num_iterations_eband_optimization: 4
  rot_stopped_vel: 0.01
  rotation_correction_threshold: 0.5
  rotation_threshold_multiplier: 1.0
  trans_stopped_vel: 0.01
  virtual_mass: 100.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

eband_accurate:
  Ctrl_Rate: 20.0
  bubble_velocity_multiplier: 2.0
  costmap_weight: 10.0
  differential_drive: true
  disallow_hysteresis: false
  eband_equilibrium_approx_max_recursion_depth: 3
  eband_equilibrium_relative_overshoot: 0.75
  eband_external_force_gain: 3.0
  eband_internal_force_gain: 2.0
  eband_min_relative_overlap: 0.7
  eband_significant_force_lower_bound: 0.15
  eband_tiny_bubble_distance: 0.01
  eband_tiny_bubble_expansion: 0.01
  in_place_trans_vel: 0.0
  k_damp: 3.5
  k_prop: 4.0
  marker_lifetime: 0.5
  max_acceleration: 0.1
  max_rotational_acceleration: 0.1
  max_translational_acceleration: 0.4
  max_vel_lin: 0.2
  max_vel_th: 0.5
  min_in_place_vel_th: 0.05
  min_vel_lin: 0.02
  min_vel_th: 0.02
  num_iterations_eband_optimization: 4
  rot_stopped_vel: 0.01
  rotation_correction_threshold: 0.5
  rotation_threshold_multiplier: 1.0
  trans_stopped_vel: 0.01
  virtual_mass: 100.0
  xy_goal_tolerance: 0.08
  yaw_goal_tolerance: 0.08

dwa:
  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_y: 0.5
  min_vel_y: -0.5
  max_rot_vel: 0.5
  min_rot_vel: 0.5
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.03